# Generated by Django 5.2.6 on 2025-10-16 03:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_model', models.CharField(max_length=100, verbose_name='Желаемая модель')),
                ('year_min', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2030)], verbose_name='Минимальный год')),
                ('year_max', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2030)], verbose_name='Максимальный год')),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Максимальный бюджет (USD)')),
                ('additional_wishes', models.TextField(blank=True, null=True, verbose_name='Дополнительные пожелания')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('searching', 'На подборе'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primer_auto.client', verbose_name='Клиент')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='primer_auto.manager', verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=50, verbose_name='Номер лота')),
                ('vin', models.CharField(max_length=17, verbose_name='VIN-номер')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('auction_country', models.CharField(choices=[('usa', 'США'), ('korea', 'Корея'), ('china', 'Китай'), ('europe', 'Европа'), ('japan', 'Япония')], max_length=20, verbose_name='Страна аукциона')),
                ('current_bid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Текущая ставка (USD)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primer_auto.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='OrderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(choices=[('search', 'Подбор'), ('auction', 'Торг/Покупка'), ('shipping', 'Доставка'), ('customs', 'Таможня'), ('registration', 'Постановка на учет')], max_length=20, verbose_name='Название этапа')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primer_auto.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Этап заказа',
                'verbose_name_plural': 'Этапы заказа',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('deposit', 'Предоплата'), ('auction', 'Оплата аукциона'), ('shipping', 'Оплата доставки'), ('customs', 'Оплата пошлины'), ('final', 'Финальный расчет')], max_length=20, verbose_name='Тип платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата платежа')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primer_auto.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('review_text', models.TextField(verbose_name='Текст отзыва')),
                ('review_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Фото автомобиля')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primer_auto.client', verbose_name='Клиент')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='primer_auto.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-review_date'],
            },
        ),
    ]
